services:
  - type: web
    name: real-estate-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn estateProject.wsgi:application --log-file - --chdir=estateProject
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: DJANGO_SETTINGS_MODULE
        value: estateProject.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "real-estate-backend.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        fromParam: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromParam: REDIS_URL
    autoDeploy: true
    healthCheckPath: /admin/
    healthCheckTimeout: 120
    staticPublishPath: staticfiles
