name: real_estate_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.0.0

  fl_chart: ^0.70.2 
  cupertino_icons: ^1.0.8
  video_player: ^2.9.3
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_charts: ^20.4.49
  image_picker: ^1.0.7
  intl: ^0.19.0
  file_picker: ^5.2.5
  image_preview: ^1.0.3
  audioplayers: ^5.2.1
  badges: ^3.1.2
  flutter_staggered_animations: ^1.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  package_info_plus: ^5.0.0
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^1.1.6
  gap: ^3.0.1 
  go_router: ^13.0.1
  flutter_vector_icons: ^2.0.0
  pdf: ^3.11.1
  printing: ^5.12.0
  csv: ^5.0.0
  path_provider: ^2.0.11
  open_file: ^3.2.1
  dio: ^5.8.0+1
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  flutter_html: ^3.0.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.0
  
  json_annotation: ^4.8.1
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  mime: ^1.0.6
  http_parser: ^4.1.2
  confetti: ^0.8.0
  flutter_animate: ^4.5.2
  photo_view: ^0.15.0
  
  flutter_local_notifications: ^17.2.2
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  web_socket_channel: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avater.webp
    - assets/gifs/intro.mp4
    - assets/images/page1.json
    - assets/images/page2.json
    - assets/images/page3.json
    - assets/images/house.json
    - assets/animations/house.json
    - assets/animations/house2.json
    - assets/animations/house3.json

  
